MvcMoviesCore/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcMoviesCore.Models
{
    public partial class Genre
    {
        public Genre() { }

        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public bool IsAdult { get; set; } = false;

        [NotMapped]
        public int Count { get; set; }

        public virtual ICollection<Movies> Movies { get; set; } = new HashSet<Movies>();
    }
}

MvcMoviesCore/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MvcMoviesCore.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MvcMoviesCore.Controllers
{
    public class GenresController : Controller
    {
        private readonly MvcMovieCoreContext _context;
        private readonly IConfiguration _configuration;
        private readonly bool _showAdult;

        public GenresController(MvcMovieCoreContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
            _showAdult = _configuration.GetValue<bool>("AppSettings:ShowAdult");
        }

        // GET: Genres
        public IActionResult Index()
        {
            return View();
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,IsAdult")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                genre.Id = Guid.NewGuid();
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description,IsAdult")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var genre = await _context.Genre.FindAsync(id);
            _context.Genre.Remove(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(Guid id)
        {
            return _context.Genre.Any(e => e.Id == id);
        }
    }
}

MvcMoviesCore/Views/Genres/Create.cshtml
@model global::MvcMoviesCore.Models.Genre

@{
    ViewData["Title"] = "Hinzufügen - Genre";
}

<h2>Genre</h2>

<h4>Hinzufügen</h4>
<hr />

<form asp-action="Create" method="post" class="card-form-horizontal">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label class="form-label">Genre:</label>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">Beschreibung:</label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-2">
                        <label class="form-label">nur für Erwachsene::</label>
                        <input asp-for="IsAdult" type="checkbox" />
                        <span asp-validation-for="IsAdult" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-1">
                        <button type="submit" title="speichern" class="fa-regular fa-floppy-disk fa-beat fa-2xl" style="color: #63E6BE; --fa-animation-duration: 2s; border: none; background-color: Transparent; " />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@* <div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Genre: </label>
                <input asp-for="Name" class="form-control" autocomplete="off" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschreibung: </label>
                <input asp-for="Description" class="form-control" autocomplete="off" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsAdult" class="control-label">nur für Erwachsene:</label>
                <input asp-for="IsAdult" type="checkbox" />
                <span asp-validation-for="IsAdult" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div> *@

<p>
    <a asp-action="Index" title="zurück zur Liste">
        <i class="fa-regular fa-circle-left fa-shake fa-2xl" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>
    </a>
</p>

MvcMoviesCore/Views/Genres/Delete.cshtml
@model global::MvcMoviesCore.Models.Genre

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcMoviesCore/Views/Genres/Details.cshtml
@model global::MvcMoviesCore.Models.Genre

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcMoviesCore/Views/Genres/Edit.cshtml
@model global::MvcMoviesCore.Models.Genre

@{
    ViewData["Title"] = "Edit - Genre";
}

<h2>Genre</h2>

<h4>Edit</h4>
<hr />
<form asp-action="Edit" method="post" class="card-form-horizontal">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-3 form-group">
                        <label class="form-label">Name:</label>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group">
                        <label class="form-label">Beschreibung:</label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="col-md-2 form-group">
                        <label class="form-label">für Erwachsene:</label>
                        <input asp-for="IsAdult" type="checkbox" />
                    </div>
                    <div class="form-group col-md-1">
                        <button type="submit" title="speichern" class="fa-regular fa-floppy-disk fa-beat fa-2xl" style="color: #63E6BE; --fa-animation-duration: 2s; border: none; background-color: Transparent; " />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<p>
    <a asp-action="Index" title="zurück zur Liste">
        <i class="fa-regular fa-circle-left fa-shake fa-2xl" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>
    </a>
</p>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcMoviesCore/Views/Genres/Index.cshtml
@model IEnumerable<Genre>

@{
    ViewData["Title"] = "Genre";
}
<div class="container-fluid">

    <h2>Genre</h2>
    <p>
        <a asp-action="Create" title="Genre hinzufügen">
            <i class="fa-regular fa-square-plus fa-beat fa-2xl" style="color: #63E6BE;  --fa-animation-duration: 2s;"></i>
        </a>
    </p>
    <table id="genreIndex" class="table table-striped cell-border table-hover compact" cellspacing="0" style="width: 100%; word-wrap:break-word; table-layout: auto;">
        <thead>
            <tr>
                <th>Datenträger</th>
                <th>Beschreibung</th>
                <th>Anzahl</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    </table>
    <div class="loader"></div>
</div>

@section Scripts
{
    <partial name="_DataTableScripts" />

    <script>
        $(document).ready(function () {
            $('#genreIndex').DataTable({
                ajax: {
                    url: appRootPath + '/api/GenreApi',
                    dataSrc: '',
                    beforeSend: function(){ $('.loader').show() },
                    complete: function(){ $('.loader').hide() }
                },
                columns: [
                    { data: 'Name' },
                    { data: 'Description' },
                    { data: 'Count' },
                    {
                        data: 'IsAdult',
                        render: function (data, type, full, meta) {
                            if (data == true) {
                                return '<input type="checkbox" checked disabled>';
                            } else {
                                return '<input type="checkbox" disabled>';
                            }
                            return data;
                        }
                    },
                    {
                        data: 'Id',
                        render: function (data, type, full, meta) {
                            if (data && type === 'display') {
                                var url = '@Url.Action("Edit", "Genres")' + '/' + data;
                                return '<a href="' + url + '" title="Genre bearbeiten">' +
                                    '<i class="fa-solid fa-pen fa-bounce" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>';
                            }
                            return '';
                        }
                    },
                    {
                        data: 'Id',
                        render: function (data, type, full, meta) {
                            if (data && type === 'display') {
                                var id = "'" + data + "'";
                                return '<button name="id" style="background-color: transparent; color: red; border: hidden"' +
                                    'onClick="deleteLink(' + id + ')" title="Datenträger löschen">' +
                                    '<i class="fa-regular fa-trash-can fa-fade" style="color: #ff0000; --fa-animation-duration: 2s;"></i>';
                            }
                            return '';
                        }
                    },
                ],
                ordering: true,
                fixedHeader: {
                    header: true,
                },
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                iDisplayLength: 10,
            });
        })

        function deleteLink(id) {
            Swal.fire({
                text: 'Genre löschen?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ja',
                cancelButtonText: 'Nein'
            }).then(function (result) {
                if (result.value) {
                    var url = appRootPath + '/api/GenreApi/' + id;
                    $.ajax({
                        url: url,
                        type: 'POST',
                        async: false,
                        statusCode: {
                            404: function () {
                                alert("function not found");
                            }
                        },
                        success: function () {
                            $('#genreIndex').DataTable().ajax.reload();
                            Swal.fire({
                                icon: 'success',
                                text: 'Genre erfolgreich gelöscht.',
                                showConfirmButton: false,
                                timer: 2000
                            })
                        },
                        error: function (response) {
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: 'Genre konnte nicht gelöscht werden!',
                                footer: response.responseText
                            })
                        }
                    })
                };
            });
        };
    </script>
}