MvcMoviesCore/Controllers/PersonTypesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMoviesCore.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MvcMoviesCore.Controllers
{
    public class PersonTypesController : Controller
    {
        #region fields

        private readonly MvcMovieCoreContext _context;

        #endregion

        #region constructor

        public PersonTypesController(MvcMovieCoreContext context)
        {
            _context = context;
        }

        #endregion

        #region public functions

        // GET: PersonTypesController
        public ActionResult Index()
        {
            return View();
            //using (var db = new MvcMovieCoreContext())
            //{
            //    IQueryable<PersonTypes> personType = db.PersonType.Include(i => i.Person);
            //    return View(await personType.ToListAsync());
            //}
        }

        //// GET: PersonTypesController/Details/5
        //public async Task<ActionResult> Details(Guid? id)
        //{
        //    using (var db = new MvcMovieCoreContext())
        //    {
        //        IQueryable<PersonTypes> personType;
        //        if (id.HasValue)
        //            personType = db.PersonType.Include(i => i.Person).Where(f => f.Id == id);
        //        else
        //            personType = db.PersonType.Include(i => i.Person);
        //        return View(await personType.ToListAsync());
        //    }
        //}

        // GET: PersonTypesController/Create
        public ActionResult Create()
        {
            return View();
            //using (var ctx = new MvcMovieCoreContext())
            //{
            //    ViewData["PersonId"] = new SelectList(ctx.Person, "Id", "Name");
            //    return View();
            //}
        }

        // POST: Person/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Name,Description")] PersonTypes personType)
        {
            if (ModelState.IsValid)
            {
                personType.Id = Guid.NewGuid();
                _context.Add(personType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personType);
        }

        // GET: PersonTypesController/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (!id.HasValue)
                return NotFound();

            var personTypes = await _context.PersonType.Include(i => i.Person).FirstOrDefaultAsync(f => f.Id == id);
            if (personTypes == null)
                return NotFound();

            return View(personTypes);
        }

        // POST: PersonTypesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, [Bind("Id,Name,Description")] PersonTypes personType)
        {
            if (id != personType.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                        _context.Update(personType);
                        await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonTypeExists(personType.Id))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["PersonId"] = new SelectList(new MvcMovieCoreContext().Person, "Id", "Name");
            return View(personType);
        }

        //// GET: PersonTypesController/Delete/5
        //public async Task<ActionResult> Delete(Guid? id)
        //{
        //    if (!id.HasValue)
        //        return NotFound();

        //    using (MvcMovieCoreContext ctx = new MvcMovieCoreContext())
        //    {
        //        var personType = await ctx.PersonType.Include(i => i.Person).FirstOrDefaultAsync(f => f.Id == id);

        //        if (personType == null)
        //            return NotFound();

        //        ViewData["PersonId"] = new SelectList(ctx.Person, "Id", "Name");
        //        return View(personType);
        //    }
        //}

        //// POST: PersonTypesController/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(Guid id)
        //{
        //    using (var ctx = new MvcMovieCoreContext())
        //    {
        //        var personType = await ctx.PersonType.FindAsync(id);
        //        ctx.PersonType.Remove(personType);
        //        await ctx.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //}

        #endregion

        #region private functions

        private bool PersonTypeExists(Guid id)
        {
            return _context.PersonType.Any(a => a.Id == id);
        }

        #endregion
    }
}

MvcMoviesCore/Views/PersonTypes/Create.cshtml
@model MvcMoviesCore.Models.PersonTypes

@{
    ViewData["Title"] = "Hinzufügen - Personentyp";
}

<h2>Personentyp</h2>

<h4>Hinzufügen</h4>
<hr />
<form asp-action="Create" method="post" class="card-form-horizontal">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="form-label">Typ:</label>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">Beschreibung:</label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-2">
                        <button type="submit" title="speichern" class="fa-regular fa-floppy-disk fa-beat fa-2xl" style="color: #63E6BE; --fa-animation-duration: 2s; border: none; background-color: Transparent; " />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<p>
    <a asp-action="Index" title="zurück zur Liste">
        <i class="fa-regular fa-circle-left fa-shake fa-xl" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>
    </a>
</p>

MvcMoviesCore/Views/PersonTypes/Edit.cshtml
@model MvcMoviesCore.Models.PersonTypes

@{
    ViewData["Title"] = "Edit - Datenträger";
}

<h2>Typ</h2>

<h4>Edit</h4>
<hr />
<form asp-action="Edit" class="card-form-horizontal" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="form-label">Name:</label>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">Beschreibung:</label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-2">
                        <button type="submit" title="speichern" class="fa-regular fa-floppy-disk fa-bounce fa-2xl" style="color: #63E6BE; --fa-animation-duration: 2s; border: none; background-color: Transparent; " />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<a asp-action="Index" title="zurück zur Liste"><i class="fa-regular fa-circle-left fa-shake fa-xl" style="color: #74C0FC; --fa-animation-duration: 2s;"></i></a>

MvcMoviesCore/Views/PersonTypes/Index.cshtml
@model IEnumerable<MvcMoviesCore.Models.PersonTypes>

@{
    ViewData["Title"] = "Typen";
}
<div class="container-fluid">

    <h2>Personentypen</h2>
    <p>
        <a asp-action="Create" title="Typ hinzufügen">
            <i class="fa-regular fa-square-plus fa-beat fa-2xl" style="color: #63E6BE;  --fa-animation-duration: 2s;"></i>
        </a>
    </p>

    <table id="personTypesIndex" class="table table-striped cell-border table-hover compact" cellspacing="0" style="width: 100%; word-wrap:break-word; table-layout: auto;">
        <thead>
            <tr>
                <th>Typ</th>
                <th>Beschreibung</th>
                <th>Anzahl</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    </table>
    <div class="loader"></div>
</div>

@section Scripts
{
    <partial name="_DataTableScripts" />

    <script>
        $(document).ready(function () {
            $('#personTypesIndex').DataTable({
                ajax: {
                    url: appRootPath + '/api/PersonTypesApi',
                    dataSrc: '',
                    beforeSend: function(){ $('.loader').show() },
                    complete: function(){ $('.loader').hide() }
                },
                columns: [
                    { data: 'Name' },
                    { data: 'Description' },
                    { data: 'Count' },
                    {
                        data: 'Id',
                        render: function (data, type, full, meta) {
                            if (data && type === 'display') {
                                var url = '@Url.Action("Edit", "PersonTypes")' + '/' + data;
                                return '<a href="' + url + '" title="Personentyp bearbeiten">' +
                                    '<i class="fa-solid fa-pen fa-bounce" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>';
                            }
                            return '';
                        }
                    },
                    {
                        data: 'Id',
                        render: function (data, type, full, meta) {
                            if (data && type === 'display') {
                                var id = "'" + data + "'";
                                return '<button name="id" style="background-color: transparent; color: red; border: hidden"' +
                                    'onClick="deleteLink(' + id + ')" title="Personentyp löschen">' +
                                    '<i class="fa-regular fa-trash-can fa-fade" style="color: #ff0000; --fa-animation-duration: 2s;"></i>';
                            }
                            return '';
                        }
                    },
                ],
                ordering: true,
                fixedHeader: {
                    header: true,
                    footer: false
                },
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                iDisplayLength: 10,
            });
        })

        function deleteLink(id) {
            Swal.fire({
                text: 'Personentyp löschen?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ja',
                cancelButtonText: 'Nein'
            }).then(function (result) {
                if (result.value) {
                    var url = appRootPath + '/api/PersonTypesApi/' + id;
                    $.ajax({
                        url: url,
                        type: 'POST',
                        async: false,
                        statusCode: {
                            404: function () {
                                Swal.fire({
                                    icon: 'warning',
                                    text: 'Function nicht gefunden.',
                                    showConfirmButton: false,
                                    timer: 2000
                                })
                            }
                        },
                        success: function () {
                            $('#personTypesIndex').DataTable().ajax.reload();
                            Swal.fire({
                                icon: 'success',
                                text: 'Personentyp erfolgreich gelöscht.',
                                showConfirmButton: false,
                                timer: 2000
                            })
                        },
                        error: function (response) {
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: 'Personentyp konnte nicht gelöscht werden!',
                                footer: response.responseText
                            })
                        }
                    })
                };
            });
        };
    </script>
}