MvcMoviesCore/Models/RecordCarrier.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcMoviesCore.Models
{
    public partial class RecordCarrier
    {
        public RecordCarrier()
        {
            Movies = new HashSet<Movies>();
        }
    
        public System.Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        [NotMapped]
        public int Count {  get; set; } 
    
        public virtual ICollection<Movies> Movies { get; set; }
    }
}

MvcMoviesCore/Controllers/RecordCarrierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MvcMoviesCore.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MvcMoviesCore.Controllers
{
    public class RecordCarrierController : Controller
    {
        #region fields

        private readonly MvcMovieCoreContext _context;
        private readonly IConfiguration _configuration;

        #endregion

        #region contructor

        public RecordCarrierController(MvcMovieCoreContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        #endregion

        #region public functions

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recordCarrier = await _context.RecordCarrier.FindAsync(id);
            if (recordCarrier == null)
            {
                return NotFound();
            }
            return View(recordCarrier);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description")] RecordCarrier recordCarrier)
        {
            if (id != recordCarrier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recordCarrier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecordCarrierExists(recordCarrier.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recordCarrier);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description")] RecordCarrier recordCarrier)
        {
            if (ModelState.IsValid)
            {
                recordCarrier.Id = Guid.NewGuid();
                _context.Add(recordCarrier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recordCarrier);
        }

        #endregion

        #region private functions

        private bool RecordCarrierExists(Guid id)
        {
            return _context.RecordCarrier.Any(x => x.Id == id);
        }

        #endregion
    }
}

MvcMoviesCore/Views/RecordCarrier/Create.cshtml
@model MvcMoviesCore.Models.RecordCarrier

@{
    ViewData["Title"] = "Hinzufügen - Datenträger";
}

<h2>Datenträger</h2>

<h4>Hinzufügen</h4>
<hr />
<form class="card-form-horizontal" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="form-label">Name:</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">Beschreibung:</label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-md-3">
                    <input asp-controller="RecordCarrier" asp-action="Create" type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
</form>
<p>
    <a asp-action="Index" title="zurück zur Liste">
        <i class="fa-regular fa-circle-left fa-shake fa-xl" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>
    </a>
</p>

MvcMoviesCore/Views/RecordCarrier/Edit.cshtml
@model MvcMoviesCore.Models.RecordCarrier

@{
    ViewData["Title"] = "Edit - Datenträger";
}

<h2>Datenträger</h2>

<h4>Edit</h4>
<hr />
<form asp-action="Edit" method="post" class="card-form-horizontal">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="form-label">Name:</label>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">Beschreibung:</label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-2">
                        <button type="submit" title="speichern" class="fa-regular fa-floppy-disk fa-beat fa-2xl" style="color: #63E6BE; --fa-animation-duration: 2s; border: none; background-color: Transparent; " />
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>
<p>
    <a asp-action="Index" title="zurück zur Liste">
        <i class="fa-regular fa-circle-left fa-shake fa-2xl" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>
    </a>
</p>

MvcMoviesCore/Views/RecordCarrier/Index.cshtml
@model IEnumerable<MvcMoviesCore.Models.RecordCarrier>

@{
    ViewData["Title"] = "Datenträger";
}
<div class="container-fluid">
    <h2>Datenträger</h2>
    <p>
        <a asp-action="Create" title="Datenträger hinzufügen">
            <i class="fa-regular fa-square-plus fa-beat fa-2xl" style="color: #63E6BE;  --fa-animation-duration: 2s;"></i>
        </a>
    </p>

    <table id="recordCarrierIndex" class="table table-striped cell-border table-hover compact" cellspacing="0" style="width: 100%; word-wrap:break-word; table-layout: auto;">
        <thead>
            <tr>
                <th>Datenträger</th>
                <th>Beschreibung</th>
                <th>Anzahl</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    </table>
    <div class="loader"></div>
</div>

@section Scripts
{
    <partial name="_DataTableScripts" />

    <script>
        $(document).ready(function () {
            $('#recordCarrierIndex').DataTable({
                ajax: {
                    url: appRootPath + '/api/RecordCarrierApi',
                    dataSrc: '',
                    beforeSend: function(){ $('.loader').show() },
                    complete: function(){ $('.loader').hide() }
                },
                columns: [
                    { data: 'Name' },
                    { data: 'Description' },
                    { data: 'Count' },
                    {
                        data: 'Id',
                        render: function (data, type, full, meta) {
                            if (data && type === 'display') {
                                var url = '@Url.Action("Edit", "RecordCarrier")' + '/' + data;
                                return '<a href="' + url + '" title="Datenträger bearbeiten">' +
                                    '<i class="fa-solid fa-pen fa-bounce" style="color: #74C0FC; --fa-animation-duration: 2s;"></i>';
                            }
                            return '';
                        }
                    },
                    {
                        data: 'Id',
                        render: function (data, type, full, meta) {
                            if (data && type === 'display') {
                                var id = "'" + data + "'";
                                return '<button name="id" style="background-color: transparent; color: red; border: hidden"' +
                                    'onClick="deleteLink(' + id + ')" title="Datenträger löschen">' +
                                    '<i class="fa-regular fa-trash-can fa-fade" style="color: #ff0000; --fa-animation-duration: 2s;"></i>';
                            }
                            return '';
                        }
                    },
                ],
                ordering: true,
                fixedHeader: {
                    header: true,
                    footer: false
                },
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                iDisplayLength: 10,
            });
        })

        function deleteLink(id) {
            Swal.fire({
                text: 'Datenträger löschen?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ja',
                cancelButtonText: 'Nein'
            }).then(function (result) {
                if (result.value) {
                    var url = appRootPath + '/api/RecordCarrierApi/' + id;
                    $.ajax({
                        url: url,
                        type: 'POST',
                        async: false,
                        statusCode: {
                            404: function () {
                                alert("function not found");
                            }
                        },
                        success: function () {
                            $('#recordCarrierIndex').DataTable().ajax.reload();
                            Swal.fire({
                                icon: 'success',
                                text: 'Datenträger erfolgreich gelöscht.',
                                showConfirmButton: false,
                                timer: 2000
                            })
                        },
                        error: function (response) {
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: 'Datenträger konnte nicht gelöscht werden!',
                                footer: response.responseText,
                            })
                        }
                    })
                };
            });
        };
    </script>
}